ERROR: unable to rename: local repo repo4 already exists
